FROM apache/airflow:1.10.14-python3.8
#https://github.com/apache/airflow/blob/4aba9c5a8b89d2827683fb4c84ac481c89ebc2b3/CHANGELOG.txt#L2065
USER root
RUN apt-get update && apt-get install -y git
USER airflow
